<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <PackageTags>NuGet;Amazon;Cloud;DynamoDB</PackageTags>
    <Description>The libraries to host BaGetter with Amazon DynamoDB as the package database.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaGetter.Core\BaGetter.Core.csproj" />
  </ItemGroup>

</Project>
